version: "3"

services:
  csrl-staging-frontend:
    build:
      context: .
      dockerfile: Dockerfile.csrl.staging
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - ./.env.frontend