// TENANT AUTHENTICATION
export const TENANT_LOADING = 'TENANT_LOADING';
export const TENANT_LOADED = 'TENANT_LOADED';
export const TENANT_AUTH_ERROR = 'TENANT_AUTH_ERROR';
export const TENANT_LOGIN_SUCCESS = 'TENANT_LOGIN_SUCCESS';
export const TENANT_LOGIN_FAIL = 'TENANT_LOGIN_FAIL';
export const TENANT_LOGOUT_SUCCESS = 'TENANT_LOGOUT_SUCCESS';
export const TENANT_REGISTER_SUCCESS = 'TENANT_REGISTER_SUCCESS';
export const TENANT_REGISTER_FAIL = 'TENANT_REGISTER_FAIL';
export const ATTEMPT_TENANT_LOGIN = 'ATTEMPT_TENANT_LOGIN';
export const ATTEMPT_TENANT_LOGIN_FAILED = 'ATTEMPT_TENANT_LOGIN_FAILED';
export const RESET_TENANT_LOGIN_FAILED = 'RESET_TENANT_LOGIN_FAILED';
export const AFTER_TENANT_LOAD = 'AFTER_TENANT_LOAD';

// USER AUTHENTICATION
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const USER_AUTH_ERROR = 'USER_AUTH_ERROR';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const ATTEMPT_USER_LOGIN = 'ATTEMPT_USER_LOGIN';
export const ATTEMPT_USER_LOGIN_FAILED = 'ATTEMPT_USER_LOGIN_FAILED';
export const RESET_USER_LOGIN_FAILED = 'RESET_USER_LOGIN_FAILED';
export const AFTER_USER_LOAD = 'AFTER_USER_LOAD';

// ERROR
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';


// CUSTOMERS
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const CUSTOMERS_LOADING = "CUSTOMERS_LOADING";


// TICKETS
export const GET_TICKETS = "GET_TICKETS";
export const ADD_TICKET = "ADD_TICKET";
export const TICKETS_LOADING = "TICKETS_LOADING";


// PRIORITIES
export const GET_PRIORITIES = "GET_PRIORITIES";
export const PRIORITIES_LOADING = "PRIORITIES_LOADING";


// CATEGORIES
export const GET_CATEGORIES = "GET_CATEGORIES";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const CATEGORIES_LOADING = "CATEGORIES_LOADING";